name: Publish

on:
  push:
    branches:
      - develop

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    name: publish
    steps:
      - name: Checkout
        uses: actions/checkout@a14471d83
        with:
          submodules: true
      - name: Build
        uses: peaceiris/actions-hugo@v0.57.2
        if: github.event.deleted == false
        with:
          args: --gc --minify --cleanDestinationDir --contentDir site/content --layoutDir site/layouts --themesDir site/themes --config site/config.toml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
